app:
  host: 127.0.0.1
  port: 3000
  journey_data_urls:
    - https://dev.hsl.fi/citybikes/od-trips-2021/2021-05.csv
    - https://dev.hsl.fi/citybikes/od-trips-2021/2021-06.csv
    - https://dev.hsl.fi/citybikes/od-trips-2021/2021-07.csv
database:
  host: 127.0.0.1
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "bikeapp"
